language: php

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
    directories:
      - "$HOME/.composer/cache"
      - "$HOME/.npm"

env:
  global:
    - PECLMONGO="mongodb-stable"

matrix:
  fast_finish: true
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'

services:
  - mongodb

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;
  - pecl channel-update pecl.php.net

install:
  # install php packages required for running YAWIK phpunit tests
  - pecl install -f ${PECLMONGO}
  - cp -v .travis/yawik.config.global.php config/autoload
  - composer install

before_script:
  # behat preparation
  - 'if [[ $COVERAGE != yes ]]; then
      composer run start-selenium --timeout=0 > /dev/null 2>&1 &
      sleep 5;
      composer run serve --timeout=0 > /dev/null 2>&1 &
      sleep 3;
    fi'
  - mkdir -p build/behat
  - chmod 777 build/behat

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat