language: php

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
    directories:
      - "$HOME/.composer/cache"
      - "$HOME/.npm"

matrix:
  fast_finish: true
  include:
  - php: '5.6'
  - php: '7.0'
  - php: '7.1'
  - php: '7.2'
  - php: '7.3'
  allow_failures:
  - php: '7.3'

services:
  - mongodb

before_install:
  - phpenv config-add ./etc/travis/yawik.ini
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi;
  - pecl channel-update pecl.php.net

install:
  # install php packages required for running YAWIK phpunit tests
  - pecl install -f mongodb
  - cp -v etc/travis/yawik.config.global.php config/autoload
  - composer install
  # @TODO remove this when auto-scripts is working again
  - composer run post-install-cmd

before_script:
  # behat preparation
  - 'if [[ $COVERAGE != yes ]]; then
      ./vendor/bin/start-selenium > /dev/null 2>&1 &
      sleep 5;
      php -S localhost:8080 -t public > /dev/null 2>&1 &
      sleep 3;
    fi'
  - mkdir -p build/behat
  - chmod 777 build/behat

after_failure:
- cd $TRAVIS_BUILD_DIR
- "./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles \"build/behat/*.log\""
- "./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles \"log/*.log\""
- "./vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles \"log/tracy/*.*\""
- "IMGUR_CLIENT_ID=bec050c54e1bb52 ./bin/imgur-uploader build/behat/*.png"

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat